import { Geist, Geist_Mono, EB_Garamond } from "next/font/google";
import "./globals.css";
import Navbar from "../components/layout/Navbar";
import BottomNavigation from "../components/layout/BottomNavigation";
import Footer from "../components/layout/Footer";
import { Reem_Kufi, Poppins } from "next/font/google";
import { AuthProvider } from "../hooks/useAuth";
import { CartProvider } from "../hooks/useCart";
import { OrdersProvider } from "../hooks/useOrders";
import FloatingChatBot from "../components/ai/FloatingChatBot";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ebGaramond = EB_Garamond({
  variable: "--font-eb-garamond",
  subsets: ["latin"],
});

const reemkufi = Reem_Kufi({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-reemkufi",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
  ],
  style: ["normal", "italic"],
  variable: "--font-poppins",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${ebGaramond.variable} ${reemkufi.variable} ${poppins.variable} antialiased pt-[76px] pb-[88px]`}
        suppressHydrationWarning={true}
      >
        <AuthProvider>
          <CartProvider>
            <OrdersProvider>
              <Navbar />
              <main className="min-h-screen">
                {children}
              </main>
              <BottomNavigation />
              <Footer />
              <FloatingChatBot />
            </OrdersProvider>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
