// Mock data for testing vendor dashboard without Supabase

export const mockVendorProfile = {
  id: 'mock-vendor-1',
  user_id: 'mock-user-1',
  business_name: 'EcoFriendly Store',
  business_type: 'Retailer',
  business_description: 'A sustainable retail store focused on eco-friendly products',
  business_address: '123 Green Street, Eco City, EC 12345',
  business_city: 'Eco City',
  business_state: 'Green State',
  business_country: 'EcoLand',
  business_pincode: '12345',
  business_phone: '+1 (555) 123-4567',
  business_email: 'contact@ecofriendlystore.com',
  business_website: 'https://ecofriendlystore.com',
  contact_person_name: 'John Green',
  contact_person_designation: 'Owner',
  contact_person_phone: '+1 (555) 123-4567',
  contact_person_email: 'john@ecofriendlystore.com',
  bank_account_number: '1234567890',
  bank_name: 'Green Bank',
  bank_ifsc_code: 'GREEN0001234',
  bank_account_holder_name: 'EcoFriendly Store',
  payment_methods: ['Credit Card', 'Debit Card', 'UPI', 'Net Banking'],
  shipping_methods: ['Standard Shipping', 'Express Shipping', 'Pickup Available'],
  return_policy: '30-day return policy for unused items',
  warranty_policy: '1-year warranty on all products',
  sustainability_commitments: ['Eco-friendly packaging', 'Carbon neutral shipping', 'Recycled materials'],
  profile_image_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
  business_logo_url: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=200&h=200&fit=crop',
  is_verified: true,
  verification_status: 'approved' as const,
  created_at: '2024-01-15T10:00:00Z',
  updated_at: '2024-01-20T15:30:00Z'
};

export const mockProducts = [
  {
    id: 'prod-1',
    vendor_id: 'mock-vendor-1',
    name: 'Bamboo Water Bottle',
    description: 'Eco-friendly bamboo water bottle with stainless steel interior. Perfect for daily hydration while reducing plastic waste.',
    short_description: 'Eco-friendly bamboo water bottle',
    category_id: 'cat-1',
    brand: 'EcoBamboo',
    sku: 'BB-WB-001',
    price: 2999,
    compare_price: 3999,
    cost_price: 1500,
    stock_quantity: 50,
    min_stock_quantity: 10,
    weight: 0.3,
    images: [
      'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&h=400&fit=crop'
    ],
    tags: ['bamboo', 'water bottle', 'eco-friendly', 'sustainable'],
    is_active: true,
    is_featured: true,
    is_digital: false,
    requires_shipping: true,
    taxable: true,
    tax_rate: 18,
    sustainability_rating: 95,
    eco_friendly_features: ['Recycled Materials', 'Biodegradable', 'Carbon Neutral'],
    certifications: ['FSC Certified', 'BPA Free'],
    materials: ['Bamboo', 'Stainless Steel'],
    packaging_type: 'Recyclable Cardboard',
    return_policy_days: 30,
    warranty_period_days: 365,
    handling_time_days: 1,
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-20T15:30:00Z'
  },
  {
    id: 'prod-2',
    vendor_id: 'mock-vendor-1',
    name: 'Organic Cotton Tote Bag',
    description: 'Handmade organic cotton tote bag perfect for grocery shopping. Durable and washable.',
    short_description: 'Organic cotton tote bag',
    category_id: 'cat-2',
    brand: 'GreenThreads',
    sku: 'CT-TB-002',
    price: 899,
    compare_price: 1299,
    cost_price: 400,
    stock_quantity: 100,
    min_stock_quantity: 20,
    weight: 0.2,
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop'
    ],
    tags: ['cotton', 'tote bag', 'organic', 'reusable'],
    is_active: true,
    is_featured: false,
    is_digital: false,
    requires_shipping: true,
    taxable: true,
    tax_rate: 12,
    sustainability_rating: 88,
    eco_friendly_features: ['Organic Materials', 'Biodegradable'],
    certifications: ['GOTS Certified', 'Organic'],
    materials: ['Organic Cotton'],
    packaging_type: 'Recyclable Paper',
    return_policy_days: 30,
    warranty_period_days: 0,
    handling_time_days: 2,
    created_at: '2024-01-16T10:00:00Z',
    updated_at: '2024-01-20T15:30:00Z'
  },
  {
    id: 'prod-3',
    vendor_id: 'mock-vendor-1',
    name: 'Solar Phone Charger',
    description: 'Portable solar charger for phones and small devices. Waterproof and durable design.',
    short_description: 'Portable solar phone charger',
    category_id: 'cat-3',
    brand: 'SunPower',
    sku: 'SP-PC-003',
    price: 4999,
    compare_price: 6999,
    cost_price: 2500,
    stock_quantity: 25,
    min_stock_quantity: 5,
    weight: 0.5,
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop'
    ],
    tags: ['solar', 'charger', 'renewable energy', 'portable'],
    is_active: true,
    is_featured: true,
    is_digital: false,
    requires_shipping: true,
    taxable: true,
    tax_rate: 18,
    sustainability_rating: 92,
    eco_friendly_features: ['Renewable Energy', 'Zero Waste'],
    certifications: ['CE Certified', 'RoHS Compliant'],
    materials: ['Solar Panels', 'Lithium Battery', 'Silicone'],
    packaging_type: 'Recyclable Cardboard',
    return_policy_days: 30,
    warranty_period_days: 730,
    handling_time_days: 1,
    created_at: '2024-01-17T10:00:00Z',
    updated_at: '2024-01-20T15:30:00Z'
  },
  {
    id: 'prod-4',
    vendor_id: 'mock-vendor-1',
    name: 'Eco-Friendly Skincare Set',
    description: 'Complete organic skincare set with natural ingredients. Includes face wash, moisturizer, and serum.',
    short_description: 'Organic skincare set',
    category_id: 'cat-4',
    brand: 'PureNature',
    sku: 'PN-SK-004',
    price: 3999,
    compare_price: 5999,
    cost_price: 2000,
    stock_quantity: 15,
    min_stock_quantity: 3,
    weight: 0.8,
    images: [
      'https://images.unsplash.com/photo-1570194065650-d99fb4bedf0a?w=400&h=400&fit=crop'
    ],
    tags: ['skincare', 'organic', 'natural', 'beauty'],
    is_active: true,
    is_featured: false,
    is_digital: false,
    requires_shipping: true,
    taxable: true,
    tax_rate: 18,
    sustainability_rating: 85,
    eco_friendly_features: ['Organic Ingredients', 'Cruelty-Free', 'Vegan'],
    certifications: ['USDA Organic', 'Cruelty-Free'],
    materials: ['Organic Aloe Vera', 'Natural Oils', 'Plant Extracts'],
    packaging_type: 'Recyclable Glass',
    return_policy_days: 30,
    warranty_period_days: 0,
    handling_time_days: 2,
    created_at: '2024-01-18T10:00:00Z',
    updated_at: '2024-01-20T15:30:00Z'
  },
  {
    id: 'prod-5',
    vendor_id: 'mock-vendor-1',
    name: 'Bamboo Cutlery Set',
    description: 'Portable bamboo cutlery set with fork, knife, spoon, and chopsticks. Perfect for on-the-go meals.',
    short_description: 'Portable bamboo cutlery',
    category_id: 'cat-5',
    brand: 'BambooLife',
    sku: 'BL-CS-005',
    price: 1299,
    compare_price: 1999,
    cost_price: 650,
    stock_quantity: 50,
    min_stock_quantity: 10,
    weight: 0.3,
    images: [
      'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400&h=400&fit=crop'
    ],
    tags: ['bamboo', 'cutlery', 'portable', 'zero waste'],
    is_active: true,
    is_featured: true,
    is_digital: false,
    requires_shipping: true,
    taxable: true,
    tax_rate: 12,
    sustainability_rating: 95,
    eco_friendly_features: ['Biodegradable', 'Reusable', 'Zero Waste'],
    certifications: ['FSC Certified', 'FDA Approved'],
    materials: ['Bamboo', 'Natural Finish'],
    packaging_type: 'Recyclable Cardboard',
    return_policy_days: 30,
    warranty_period_days: 0,
    handling_time_days: 1,
    created_at: '2024-01-19T10:00:00Z',
    updated_at: '2024-01-20T15:30:00Z'
  },
  {
    id: 'prod-6',
    vendor_id: 'mock-vendor-1',
    name: 'Recycled Paper Notebook',
    description: 'Eco-friendly notebook made from 100% recycled paper. Perfect for notes, journaling, and sketching.',
    short_description: 'Recycled paper notebook',
    category_id: 'cat-6',
    brand: 'EcoWrite',
    sku: 'EW-NB-006',
    price: 599,
    compare_price: 899,
    cost_price: 300,
    stock_quantity: 100,
    min_stock_quantity: 20,
    weight: 0.4,
    images: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=400&fit=crop'
    ],
    tags: ['notebook', 'recycled', 'paper', 'stationery'],
    is_active: true,
    is_featured: false,
    is_digital: false,
    requires_shipping: true,
    taxable: true,
    tax_rate: 12,
    sustainability_rating: 90,
    eco_friendly_features: ['Recycled Materials', 'Biodegradable', 'Sustainable'],
    certifications: ['FSC Recycled', 'PEFC Certified'],
    materials: ['Recycled Paper', 'Soy-based Ink'],
    packaging_type: 'Recyclable Paper',
    return_policy_days: 30,
    warranty_period_days: 0,
    handling_time_days: 1,
    created_at: '2024-01-20T10:00:00Z',
    updated_at: '2024-01-20T15:30:00Z'
  },
  {
    id: 'prod-7',
    vendor_id: 'mock-vendor-1',
    name: 'Organic Cotton T-Shirt',
    description: 'Comfortable organic cotton t-shirt made from 100% organic cotton. Available in multiple colors.',
    short_description: 'Organic cotton t-shirt',
    category_id: 'cat-7',
    brand: 'EcoWear',
    sku: 'EW-TS-007',
    price: 1999,
    compare_price: 2999,
    cost_price: 1000,
    stock_quantity: 75,
    min_stock_quantity: 15,
    weight: 0.2,
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=400&fit=crop'
    ],
    tags: ['t-shirt', 'organic cotton', 'clothing', 'sustainable'],
    is_active: true,
    is_featured: true,
    is_digital: false,
    requires_shipping: true,
    taxable: true,
    tax_rate: 12,
    sustainability_rating: 88,
    eco_friendly_features: ['Organic Cotton', 'Fair Trade', 'Biodegradable'],
    certifications: ['GOTS Certified', 'Fair Trade'],
    materials: ['Organic Cotton', 'Natural Dyes'],
    packaging_type: 'Recyclable Paper',
    return_policy_days: 30,
    warranty_period_days: 0,
    handling_time_days: 2,
    created_at: '2024-01-21T10:00:00Z',
    updated_at: '2024-01-20T15:30:00Z'
  },
  {
    id: 'prod-8',
    vendor_id: 'mock-vendor-1',
    name: 'Stainless Steel Straw Set',
    description: 'Set of 4 stainless steel straws with cleaning brush. Perfect alternative to plastic straws.',
    short_description: 'Stainless steel straw set',
    category_id: 'cat-8',
    brand: 'SteelStraw',
    sku: 'SS-ST-008',
    price: 799,
    compare_price: 1299,
    cost_price: 400,
    stock_quantity: 60,
    min_stock_quantity: 12,
    weight: 0.1,
    images: [
      'https://images.unsplash.com/photo-1581833971358-2c8b550f87b3?w=400&h=400&fit=crop'
    ],
    tags: ['straws', 'stainless steel', 'reusable', 'zero waste'],
    is_active: true,
    is_featured: false,
    is_digital: false,
    requires_shipping: true,
    taxable: true,
    tax_rate: 12,
    sustainability_rating: 92,
    eco_friendly_features: ['Reusable', 'Durable', 'Zero Waste'],
    certifications: ['FDA Approved', 'BPA Free'],
    materials: ['Stainless Steel', 'Silicone Tips'],
    packaging_type: 'Recyclable Cardboard',
    return_policy_days: 30,
    warranty_period_days: 365,
    handling_time_days: 1,
    created_at: '2024-01-22T10:00:00Z',
    updated_at: '2024-01-20T15:30:00Z'
  }
];

export const mockOrders = [
  {
    id: 'order-1',
    order_number: 'ORD-2024-001',
    customer_id: 'customer-1',
    customer_name: 'Alice Johnson',
    customer_email: 'alice@example.com',
    customer_phone: '+1 (555) 987-6543',
    status: 'delivered' as const,
    payment_status: 'paid' as const,
    payment_method: 'Credit Card',
    payment_reference: 'PAY-123456',
    subtotal: 3898,
    tax_amount: 701.64,
    shipping_amount: 100,
    discount_amount: 0,
    total_amount: 4699.64,
    currency: 'INR',
    tracking_number: 'TRK123456789',
    shipping_carrier: 'EcoShip',
    estimated_delivery_date: '2024-01-25',
    actual_delivery_date: '2024-01-24',
    created_at: '2024-01-20T10:00:00Z',
    updated_at: '2024-01-24T16:30:00Z',
    items: [
      {
        id: 'item-1',
        order_id: 'order-1',
        product_id: 'prod-1',
        product_name: 'Bamboo Water Bottle',
        product_sku: 'BB-WB-001',
        quantity: 1,
        unit_price: 2999,
        total_price: 2999,
        vendor_id: 'mock-vendor-1',
        created_at: '2024-01-20T10:00:00Z'
      }
    ],
    addresses: [
      {
        id: 'addr-1',
        order_id: 'order-1',
        type: 'shipping' as const,
        first_name: 'Alice',
        last_name: 'Johnson',
        address_line_1: '456 Green Avenue',
        city: 'Eco City',
        state: 'Green State',
        country: 'EcoLand',
        postal_code: '12345',
        phone: '+1 (555) 987-6543',
        email: 'alice@example.com'
      }
    ]
  },
  {
    id: 'order-2',
    order_number: 'ORD-2024-002',
    customer_id: 'customer-2',
    customer_name: 'Bob Smith',
    customer_email: 'bob@example.com',
    customer_phone: '+1 (555) 456-7890',
    status: 'shipped' as const,
    payment_status: 'paid' as const,
    payment_method: 'UPI',
    payment_reference: 'PAY-789012',
    subtotal: 1798,
    tax_amount: 215.76,
    shipping_amount: 50,
    discount_amount: 0,
    total_amount: 2063.76,
    currency: 'INR',
    tracking_number: 'TRK987654321',
    shipping_carrier: 'FastGreen',
    estimated_delivery_date: '2024-01-28',
    created_at: '2024-01-22T14:30:00Z',
    updated_at: '2024-01-23T09:15:00Z',
    items: [
      {
        id: 'item-2',
        order_id: 'order-2',
        product_id: 'prod-2',
        product_name: 'Organic Cotton Tote Bag',
        product_sku: 'CT-TB-002',
        quantity: 2,
        unit_price: 899,
        total_price: 1798,
        vendor_id: 'mock-vendor-1',
        created_at: '2024-01-22T14:30:00Z'
      }
    ],
    addresses: [
      {
        id: 'addr-2',
        order_id: 'order-2',
        type: 'shipping' as const,
        first_name: 'Bob',
        last_name: 'Smith',
        address_line_1: '789 Sustainable Street',
        city: 'Green Valley',
        state: 'Eco State',
        country: 'EcoLand',
        postal_code: '54321',
        phone: '+1 (555) 456-7890',
        email: 'bob@example.com'
      }
    ]
  },
  {
    id: 'order-3',
    order_number: 'ORD-2024-003',
    customer_id: 'customer-3',
    customer_name: 'Emma Wilson',
    customer_email: 'emma@example.com',
    customer_phone: '+1 (555) 123-4567',
    status: 'processing' as const,
    payment_status: 'paid' as const,
    payment_method: 'Debit Card',
    payment_reference: 'PAY-345678',
    subtotal: 4999,
    tax_amount: 899.82,
    shipping_amount: 100,
    discount_amount: 0,
    total_amount: 5998.82,
    currency: 'INR',
    tracking_number: null,
    shipping_carrier: null,
    estimated_delivery_date: '2024-01-30',
    created_at: '2024-01-23T11:15:00Z',
    updated_at: '2024-01-23T11:15:00Z',
    items: [
      {
        id: 'item-3',
        order_id: 'order-3',
        product_id: 'prod-3',
        product_name: 'Solar Phone Charger',
        product_sku: 'SP-PC-003',
        quantity: 1,
        unit_price: 4999,
        total_price: 4999,
        vendor_id: 'mock-vendor-1',
        created_at: '2024-01-23T11:15:00Z'
      }
    ],
    addresses: [
      {
        id: 'addr-3',
        order_id: 'order-3',
        type: 'shipping' as const,
        first_name: 'Emma',
        last_name: 'Wilson',
        address_line_1: '321 Eco Lane',
        city: 'Solar City',
        state: 'Renewable State',
        country: 'EcoLand',
        postal_code: '54321',
        phone: '+1 (555) 123-4567',
        email: 'emma@example.com'
      }
    ]
  },
  {
    id: 'order-4',
    order_number: 'ORD-2024-004',
    customer_id: 'customer-4',
    customer_name: 'David Brown',
    customer_email: 'david@example.com',
    customer_phone: '+1 (555) 234-5678',
    status: 'pending' as const,
    payment_status: 'pending' as const,
    payment_method: 'UPI',
    payment_reference: null,
    subtotal: 5998,
    tax_amount: 1079.64,
    shipping_amount: 100,
    discount_amount: 0,
    total_amount: 7177.64,
    currency: 'INR',
    tracking_number: null,
    shipping_carrier: null,
    estimated_delivery_date: '2024-02-01',
    created_at: '2024-01-24T09:30:00Z',
    updated_at: '2024-01-24T09:30:00Z',
    items: [
      {
        id: 'item-4',
        order_id: 'order-4',
        product_id: 'prod-1',
        product_name: 'Bamboo Water Bottle',
        product_sku: 'BB-WB-001',
        quantity: 2,
        unit_price: 2999,
        total_price: 5998,
        vendor_id: 'mock-vendor-1',
        created_at: '2024-01-24T09:30:00Z'
      }
    ],
    addresses: [
      {
        id: 'addr-4',
        order_id: 'order-4',
        type: 'shipping' as const,
        first_name: 'David',
        last_name: 'Brown',
        address_line_1: '654 Forest Drive',
        city: 'Wood City',
        state: 'Nature State',
        country: 'EcoLand',
        postal_code: '67890',
        phone: '+1 (555) 234-5678',
        email: 'david@example.com'
      }
    ]
  },
  {
    id: 'order-5',
    order_number: 'ORD-2024-005',
    customer_id: 'customer-5',
    customer_name: 'Lisa Garcia',
    customer_email: 'lisa@example.com',
    customer_phone: '+1 (555) 345-6789',
    status: 'delivered' as const,
    payment_status: 'paid' as const,
    payment_method: 'Credit Card',
    payment_reference: 'PAY-456789',
    subtotal: 1798,
    tax_amount: 215.76,
    shipping_amount: 50,
    discount_amount: 0,
    total_amount: 2063.76,
    currency: 'INR',
    tracking_number: 'TRK555666777',
    shipping_carrier: 'EcoExpress',
    estimated_delivery_date: '2024-01-26',
    actual_delivery_date: '2024-01-25',
    created_at: '2024-01-21T16:45:00Z',
    updated_at: '2024-01-25T14:20:00Z',
    items: [
      {
        id: 'item-5',
        order_id: 'order-5',
        product_id: 'prod-2',
        product_name: 'Organic Cotton Tote Bag',
        product_sku: 'CT-TB-002',
        quantity: 2,
        unit_price: 899,
        total_price: 1798,
        vendor_id: 'mock-vendor-1',
        created_at: '2024-01-21T16:45:00Z'
      }
    ],
    addresses: [
      {
        id: 'addr-5',
        order_id: 'order-5',
        type: 'shipping' as const,
        first_name: 'Lisa',
        last_name: 'Garcia',
        address_line_1: '987 Green Street',
        city: 'Leaf City',
        state: 'Green State',
        country: 'EcoLand',
        postal_code: '11111',
        phone: '+1 (555) 345-6789',
        email: 'lisa@example.com'
      }
    ]
  },
  {
    id: 'order-6',
    order_number: 'ORD-2024-006',
    customer_id: 'customer-6',
    customer_name: 'James Taylor',
    customer_email: 'james@example.com',
    customer_phone: '+1 (555) 456-7890',
    status: 'shipped' as const,
    payment_status: 'paid' as const,
    payment_method: 'Net Banking',
    payment_reference: 'PAY-567890',
    subtotal: 11997,
    tax_amount: 2159.46,
    shipping_amount: 150,
    discount_amount: 500,
    total_amount: 13806.46,
    currency: 'INR',
    tracking_number: 'TRK888999000',
    shipping_carrier: 'GreenLogistics',
    estimated_delivery_date: '2024-01-29',
    created_at: '2024-01-22T13:20:00Z',
    updated_at: '2024-01-23T10:30:00Z',
    items: [
      {
        id: 'item-6',
        order_id: 'order-6',
        product_id: 'prod-1',
        product_name: 'Bamboo Water Bottle',
        product_sku: 'BB-WB-001',
        quantity: 2,
        unit_price: 2999,
        total_price: 5998,
        vendor_id: 'mock-vendor-1',
        created_at: '2024-01-22T13:20:00Z'
      },
      {
        id: 'item-7',
        order_id: 'order-6',
        product_id: 'prod-3',
        product_name: 'Solar Phone Charger',
        product_sku: 'SP-PC-003',
        quantity: 1,
        unit_price: 4999,
        total_price: 4999,
        vendor_id: 'mock-vendor-1',
        created_at: '2024-01-22T13:20:00Z'
      }
    ],
    addresses: [
      {
        id: 'addr-6',
        order_id: 'order-6',
        type: 'shipping' as const,
        first_name: 'James',
        last_name: 'Taylor',
        address_line_1: '147 Eco Avenue',
        city: 'Garden City',
        state: 'Eco State',
        country: 'EcoLand',
        postal_code: '22222',
        phone: '+1 (555) 456-7890',
        email: 'james@example.com'
      }
    ]
  },
  {
    id: 'order-7',
    order_number: 'ORD-2024-007',
    customer_id: 'customer-7',
    customer_name: 'Maria Rodriguez',
    customer_email: 'maria@example.com',
    customer_phone: '+1 (555) 567-8901',
    status: 'cancelled' as const,
    payment_status: 'refunded' as const,
    payment_method: 'Credit Card',
    payment_reference: 'PAY-678901',
    subtotal: 4999,
    tax_amount: 899.82,
    shipping_amount: 100,
    discount_amount: 0,
    total_amount: 5998.82,
    currency: 'INR',
    tracking_number: null,
    shipping_carrier: null,
    estimated_delivery_date: null,
    created_at: '2024-01-20T14:10:00Z',
    updated_at: '2024-01-21T09:30:00Z',
    items: [
      {
        id: 'item-8',
        order_id: 'order-7',
        product_id: 'prod-3',
        product_name: 'Solar Phone Charger',
        product_sku: 'SP-PC-003',
        quantity: 1,
        unit_price: 4999,
        total_price: 4999,
        vendor_id: 'mock-vendor-1',
        created_at: '2024-01-20T14:10:00Z'
      }
    ],
    addresses: [
      {
        id: 'addr-7',
        order_id: 'order-7',
        type: 'shipping' as const,
        first_name: 'Maria',
        last_name: 'Rodriguez',
        address_line_1: '258 Solar Street',
        city: 'Forest City',
        state: 'Nature State',
        country: 'EcoLand',
        postal_code: '33333',
        phone: '+1 (555) 567-8901',
        email: 'maria@example.com'
      }
    ]
  },
  {
    id: 'order-8',
    order_number: 'ORD-2024-008',
    customer_id: 'customer-8',
    customer_name: 'Robert Kim',
    customer_email: 'robert@example.com',
    customer_phone: '+1 (555) 678-9012',
    status: 'delivered' as const,
    payment_status: 'paid' as const,
    payment_method: 'UPI',
    payment_reference: 'PAY-789012',
    subtotal: 2697,
    tax_amount: 323.64,
    shipping_amount: 50,
    discount_amount: 0,
    total_amount: 3070.64,
    currency: 'INR',
    tracking_number: 'TRK111222333',
    shipping_carrier: 'EcoShip',
    estimated_delivery_date: '2024-01-27',
    actual_delivery_date: '2024-01-26',
    created_at: '2024-01-19T12:30:00Z',
    updated_at: '2024-01-26T11:45:00Z',
    items: [
      {
        id: 'item-9',
        order_id: 'order-8',
        product_id: 'prod-2',
        product_name: 'Organic Cotton Tote Bag',
        product_sku: 'CT-TB-002',
        quantity: 3,
        unit_price: 899,
        total_price: 2697,
        vendor_id: 'mock-vendor-1',
        created_at: '2024-01-19T12:30:00Z'
      }
    ],
    addresses: [
      {
        id: 'addr-8',
        order_id: 'order-8',
        type: 'shipping' as const,
        first_name: 'Robert',
        last_name: 'Kim',
        address_line_1: '369 Willow Way',
        city: 'Leaf City',
        state: 'Green State',
        country: 'EcoLand',
        postal_code: '44444',
        phone: '+1 (555) 678-9012',
        email: 'robert@example.com'
      }
    ]
  },
  {
    id: 'order-9',
    order_number: 'ORD-2024-009',
    customer_id: 'customer-9',
    customer_name: 'Jennifer Lee',
    customer_email: 'jennifer@example.com',
    customer_phone: '+1 (555) 789-0123',
    status: 'processing' as const,
    payment_status: 'paid' as const,
    payment_method: 'Debit Card',
    payment_reference: 'PAY-890123',
    subtotal: 14995,
    tax_amount: 2699.10,
    shipping_amount: 200,
    discount_amount: 1000,
    total_amount: 16894.10,
    currency: 'INR',
    tracking_number: null,
    shipping_carrier: null,
    estimated_delivery_date: '2024-02-02',
    created_at: '2024-01-24T08:15:00Z',
    updated_at: '2024-01-24T08:15:00Z',
    items: [
      {
        id: 'item-10',
        order_id: 'order-9',
        product_id: 'prod-1',
        product_name: 'Bamboo Water Bottle',
        product_sku: 'BB-WB-001',
        quantity: 5,
        unit_price: 2999,
        total_price: 14995,
        vendor_id: 'mock-vendor-1',
        created_at: '2024-01-24T08:15:00Z'
      }
    ],
    addresses: [
      {
        id: 'addr-9',
        order_id: 'order-9',
        type: 'shipping' as const,
        first_name: 'Jennifer',
        last_name: 'Lee',
        address_line_1: '741 Ash Street',
        city: 'Wood City',
        state: 'Forest State',
        country: 'EcoLand',
        postal_code: '55555',
        phone: '+1 (555) 789-0123',
        email: 'jennifer@example.com'
      }
    ]
  },
  {
    id: 'order-10',
    order_number: 'ORD-2024-010',
    customer_id: 'customer-10',
    customer_name: 'Michael Davis',
    customer_email: 'michael@example.com',
    customer_phone: '+1 (555) 890-1234',
    status: 'shipped' as const,
    payment_status: 'paid' as const,
    payment_method: 'Credit Card',
    payment_reference: 'PAY-901234',
    subtotal: 14995,
    tax_amount: 2699.10,
    shipping_amount: 150,
    discount_amount: 0,
    total_amount: 17844.10,
    currency: 'INR',
    tracking_number: 'TRK444555666',
    shipping_carrier: 'FastEco',
    estimated_delivery_date: '2024-01-31',
    created_at: '2024-01-18T15:45:00Z',
    updated_at: '2024-01-20T12:20:00Z',
    items: [
      {
        id: 'item-11',
        order_id: 'order-10',
        product_id: 'prod-1',
        product_name: 'Bamboo Water Bottle',
        product_sku: 'BB-WB-001',
        quantity: 3,
        unit_price: 2999,
        total_price: 8997,
        vendor_id: 'mock-vendor-1',
        created_at: '2024-01-18T15:45:00Z'
      },
      {
        id: 'item-12',
        order_id: 'order-10',
        product_id: 'prod-2',
        product_name: 'Organic Cotton Tote Bag',
        product_sku: 'CT-TB-002',
        quantity: 4,
        unit_price: 899,
        total_price: 3596,
        vendor_id: 'mock-vendor-1',
        created_at: '2024-01-18T15:45:00Z'
      },
      {
        id: 'item-13',
        order_id: 'order-10',
        product_id: 'prod-3',
        product_name: 'Solar Phone Charger',
        product_sku: 'SP-PC-003',
        quantity: 1,
        unit_price: 4999,
        total_price: 4999,
        vendor_id: 'mock-vendor-1',
        created_at: '2024-01-18T15:45:00Z'
      }
    ],
    addresses: [
      {
        id: 'addr-10',
        order_id: 'order-10',
        type: 'shipping' as const,
        first_name: 'Michael',
        last_name: 'Davis',
        address_line_1: '852 Poplar Place',
        city: 'Garden City',
        state: 'Eco State',
        country: 'EcoLand',
        postal_code: '66666',
        phone: '+1 (555) 890-1234',
        email: 'michael@example.com'
      }
    ]
  },
  {
    id: 'order-11',
    order_number: 'ORD-2024-011',
    customer_id: 'customer-11',
    customer_name: 'Amanda White',
    customer_email: 'amanda@example.com',
    customer_phone: '+1 (555) 901-2345',
    status: 'pending' as const,
    payment_status: 'pending' as const,
    payment_method: 'UPI',
    payment_reference: null,
    subtotal: 1798,
    tax_amount: 215.76,
    shipping_amount: 50,
    discount_amount: 0,
    total_amount: 2063.76,
    currency: 'INR',
    tracking_number: null,
    shipping_carrier: null,
    estimated_delivery_date: '2024-02-03',
    created_at: '2024-01-25T10:00:00Z',
    updated_at: '2024-01-25T10:00:00Z',
    items: [
      {
        id: 'item-14',
        order_id: 'order-11',
        product_id: 'prod-2',
        product_name: 'Organic Cotton Tote Bag',
        product_sku: 'CT-TB-002',
        quantity: 2,
        unit_price: 899,
        total_price: 1798,
        vendor_id: 'mock-vendor-1',
        created_at: '2024-01-25T10:00:00Z'
      }
    ],
    addresses: [
      {
        id: 'addr-11',
        order_id: 'order-11',
        type: 'shipping' as const,
        first_name: 'Amanda',
        last_name: 'White',
        address_line_1: '963 Cherry Court',
        city: 'Tree City',
        state: 'Nature State',
        country: 'EcoLand',
        postal_code: '77777',
        phone: '+1 (555) 901-2345',
        email: 'amanda@example.com'
      }
    ]
  },
  {
    id: 'order-12',
    order_number: 'ORD-2024-012',
    customer_id: 'customer-12',
    customer_name: 'Christopher Moore',
    customer_email: 'christopher@example.com',
    customer_phone: '+1 (555) 012-3456',
    status: 'delivered' as const,
    payment_status: 'paid' as const,
    payment_method: 'Net Banking',
    payment_reference: 'PAY-012345',
    subtotal: 17994,
    tax_amount: 3238.92,
    shipping_amount: 100,
    discount_amount: 0,
    total_amount: 21332.92,
    currency: 'INR',
    tracking_number: 'TRK777888999',
    shipping_carrier: 'GreenLogistics',
    estimated_delivery_date: '2024-01-28',
    actual_delivery_date: '2024-01-27',
    created_at: '2024-01-17T14:20:00Z',
    updated_at: '2024-01-27T16:10:00Z',
    items: [
      {
        id: 'item-15',
        order_id: 'order-12',
        product_id: 'prod-1',
        product_name: 'Bamboo Water Bottle',
        product_sku: 'BB-WB-001',
        quantity: 6,
        unit_price: 2999,
        total_price: 17994,
        vendor_id: 'mock-vendor-1',
        created_at: '2024-01-17T14:20:00Z'
      }
    ],
    addresses: [
      {
        id: 'addr-12',
        order_id: 'order-12',
        type: 'shipping' as const,
        first_name: 'Christopher',
        last_name: 'Moore',
        address_line_1: '159 Hickory Hill',
        city: 'Forest City',
        state: 'Green State',
        country: 'EcoLand',
        postal_code: '88888',
        phone: '+1 (555) 012-3456',
        email: 'christopher@example.com'
      }
    ]
  }
];

export const mockOrderStats = {
  total_orders: 12,
  pending_orders: 2,
  processing_orders: 2,
  shipped_orders: 3,
  delivered_orders: 4,
  cancelled_orders: 1,
  total_revenue: 125678.90,
  average_order_value: 10473.24,
  orders_this_month: 8,
  revenue_this_month: 85678.75
};

export const mockCategories = [
  { id: 'cat-1', name: 'Water Bottles', description: 'Eco-friendly water bottles', is_active: true },
  { id: 'cat-2', name: 'Bags & Accessories', description: 'Sustainable bags and accessories', is_active: true },
  { id: 'cat-3', name: 'Solar Products', description: 'Solar-powered devices', is_active: true },
  { id: 'cat-4', name: 'Skincare & Beauty', description: 'Organic and natural skincare products', is_active: true },
  { id: 'cat-5', name: 'Kitchen & Dining', description: 'Eco-friendly kitchen and dining accessories', is_active: true },
  { id: 'cat-6', name: 'Stationery', description: 'Sustainable office and stationery supplies', is_active: true },
  { id: 'cat-7', name: 'Clothing', description: 'Organic and sustainable clothing', is_active: true },
  { id: 'cat-8', name: 'Zero Waste', description: 'Zero waste lifestyle products', is_active: true }
];
